CREATE TABLE RENT
(
    rent_id int AUTO_INCREMENT PRIMARY KEY NOT NULL,
    apartment_id int NOT NULL,
    client_id int NOT NULL,
    CONSTRAINT R_APARTMENT_ID_FK FOREIGN KEY (apartment_id) REFERENCES APARTMENTS (APARTMENT_ID) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT R_CLIENT_ID_FK FOREIGN KEY (client_id) REFERENCES CLIENTS (CLIENT_ID) ON DELETE SET NULL ON UPDATE CASCADE
);